language: python
python:
  - "3.5"
env:
  matrix:
    - TOXENV=py27
    - TOXENV=py32
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=pypy
    - TOXENV=pypy3
    - TOXENV=flake8
install:
    - travis_retry make install
script:
    - make test
